# Generated by Django 3.2.7 on 2021-10-16 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('heading0', models.CharField(max_length=8000)),
                ('c_heading0', models.CharField(max_length=8000)),
                ('heading1', models.CharField(max_length=8000)),
                ('c_heading1', models.CharField(max_length=8000)),
                ('heading2', models.CharField(max_length=8000)),
                ('c_heading2', models.CharField(max_length=8000)),
                ('publ_date', models.DateField(default=datetime.datetime(2021, 10, 16, 20, 24, 42, 721154), verbose_name='Date')),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
