# Generated by Django 3.2.7 on 2021-10-16 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publ_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 16, 20, 27, 45, 162894)),
        ),
    ]
