# Generated by Django 3.2.7 on 2021-10-16 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogpost_publ_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publ_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 16, 15, 2, 36, 210493, tzinfo=utc)),
        ),
    ]
