# Generated by Django 3.2.7 on 2021-10-17 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20211016_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
