# Generated by Django 3.2.7 on 2021-10-17 07:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogs', '0005_delete_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=5000)),
                ('heading0', models.CharField(max_length=8000)),
                ('c_heading0', models.CharField(max_length=8000)),
                ('heading1', models.CharField(max_length=8000)),
                ('c_heading1', models.CharField(max_length=8000)),
                ('heading2', models.CharField(max_length=8000)),
                ('c_heading2', models.CharField(max_length=8000)),
                ('publ_date', models.DateField(default=datetime.datetime(2021, 10, 17, 7, 2, 27, 739610, tzinfo=utc))),
                ('thumbnail', models.ImageField(default='', upload_to='blogs/images')),
            ],
        ),
    ]
