# Generated by Django 3.2.7 on 2021-09-27 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publ_date',
            field=models.DateField(default=datetime.datetime(2021, 9, 27, 22, 48, 27, 476153), verbose_name='Date'),
        ),
    ]
