# Generated by Django 3.2.7 on 2021-10-09 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20211009_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publ_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 9, 18, 29, 11, 447685), verbose_name='Date'),
        ),
    ]
