# Generated by Django 3.2.7 on 2021-10-16 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211013_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='publ_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 16, 20, 24, 42, 611744), verbose_name='Date'),
        ),
    ]
